Repository scylladb/scylla-ccm, pull requests merged in 2019-12, with the labels that each got.

#194 Missing comma in `node.stress()`
  ccmlib/node.py
Labels: bug

#195 `SCYLLA-VERSION-FILE` is in a diffrent location in reloc packages
  ccmlib/common.py
Labels: bug

#200 Remove pause() and resume() from ScyllaNode
  ccmlib/scylla_node.py
Labels: Ready For Review, bug

#199 node cleanups: update_config, new_node, update_pid
  ccmlib/cluster.py
  ccmlib/node.py
  ccmlib/scylla_cluster.py
  ccmlib/scylla_node.py
Labels: Ready For Review
